### ISSUE TITLE
Simplify draw AtlasRegion

### ISSUE THREAD

**Issue by Matoran** [udacity/ud406#19]
Hello you can replace your "horrific" version(2.1.08 TextureAtlasExercise)
```       
batch.draw(
                standingRight.getTexture(),
                0,
                0,
                0,
                0,
                standingRight.getRegionWidth(),
                standingRight.getRegionHeight(),
                1,
                1,
                0,
                standingRight.getRegionX(),
                standingRight.getRegionY(),
                standingRight.getRegionWidth(),
                standingRight.getRegionHeight(),
                false,
                false);
```

by

`batch.draw(standingRight, 0, 0);`

You can do that because AtlasRegion is a subclass of TextureRegion.

**Comment by jwill** [comment]
The long form was a conscious choice to demonstrate more explicitly what is happening. We appreciate you taking the time to create the issue but we won't be implementing this change.

**Comment by looscrew** [comment]
I join the OP's wonder. I wasted quite some time trying to figure out why we need to pass the 'containing image' ( region.getTexture() ) while we already have the region itself. Your "conscious choice" creates confusion. If you're not going to change it, at the very least you could mention below the video that there's a simpler way to accomplish the same thing.

Note to self: next time check the Issues page first.
