### ISSUE TITLE
Error with FileLoading decrypting

### ISSUE THREAD

**Issue by craigjcannon** [udacity/ud406#2]
I ran into this error when decrypting the string in punchline file in FileLoading exercise. I'm running on Arch Linux setup by the way, if that helps.

    12-20 06:29:18.420 29481-29502/com.udacity.gamedev.fileloading.android E/AndroidRuntime:     FATAL EXCEPTION: GLThread 16759
    12-20 06:29:18.420 29481-29502/com.udacity.gamedev.fileloading.android E/AndroidRuntime: Process: com.udacity.gamedev.fileloading.android, PID: 29481
    12-20 06:29:18.420 29481-29502/com.udacity.gamedev.fileloading.android E/AndroidRuntime: java.lang.NoSuchMethodError: No static method encodeBase64String([B)Ljava/lang/String; in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.boot.jar)
    12-20 06:29:18.420 29481-29502/com.udacity.gamedev.fileloading.android E/AndroidRuntime:     at com.udacity.gamedev.fileloading.FileLoading.encrypt(FileLoading.java:32)
    12-20 06:29:18.420 29481-29502/com.udacity.gamedev.fileloading.android E/AndroidRuntime:     at com.udacity.gamedev.fileloading.FileLoading.create(FileLoading.java:56)
    12-20 06:29:18.420 29481-29502/com.udacity.gamedev.fileloading.android E/AndroidRuntime:     at com.badlogic.gdx.backends.android.AndroidGraphics.onSurfaceChanged(AndroidGraphics.java:243)
    12-20 06:29:18.420 29481-29502/com.udacity.gamedev.fileloading.android E/AndroidRuntime:     at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1519)
    12-20 06:29:18.420 29481-29502/com.udacity.gamedev.fileloading.android E/AndroidRuntime:     at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

**Comment by jwill** [comment]
This example only works on the desktop target.

Android packages its own set of apache commons and strips the Base64 encoding from it. Base64 encoding is located in android.util.Base64. Even if you add the commons line to the gradle dependencies, Android will favor its local version

**Comment by JeremySilverTongue** [comment]
Made that clear in the README, and added a more helpful error message if the encrypt/decrypt functions are used on Android.
