### ISSUE TITLE
assets/images directory is missing

### ISSUE THREAD

**Issue by stanishev** [udacity/ud406#5]
Hello Jeremy, the android/assets/images/directory is missing for the 2.2.03-Exercise-AssetLoading project.

**Comment by JeremySilverTongue** [comment]
Hey Stanishev,

Setting up that directory is part of the exercise! Check out these lines:

https://github.com/udacity/ud406/blob/b0f4e34142ae3cae3c52f6087ea958916f370a38/2.2.03-Exercise-AssetLoading/build.gradle#L101-L111
