### ISSUE TITLE
have to make absolute paths for packer task to get packer to work

### ISSUE THREAD

**Issue by LetterRip** [udacity/ud406#6]
Hi, I have to edit the packer task and add 'C:/path/to/project/' to the start of each directory, otherwise the packer task fails for the desktop build when run from Android Studio.  Setting the working directory (I've tried a number of different possibilities) doesn't help.

**Comment by JeremySilverTongue** [comment]
I think I've resolved this issue in https://github.com/udacity/ud406/commit/a5e8c95db587060767ab167e9f358672dfcc0bb8

Sorry for taking so long to get to it. Thanks a ton for the issue report!
